services:
  - type: web
    name: vigilia
    runtime: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
    autoDeploy: true
