PEP_ROLES: frozenset[str] = frozenset({
    "diputado",
    "diputada",
    "senador",
    "senadora",
    "concejal",
    "concejala",
    "alcalde",
    "alcaldesa",
    "presidente",
    "presidenta",
    "ministro",
    "ministra",
    "consejero",
    "consejera",
    "secretario de estado",
    "subsecretario",
    "director general",
})
